#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
easy_admin:
    entities:
      Livres:
        class: App\Entity\Livres
        list:
          fields:        
            - { property: 'photo', type: 'image', base_path: '%%app.path.photo_image%' }

        show:
          fields:
            - { property: 'photo', type: 'image', base_path: '%app.path.photo_image%' }

        form:
          fields:
            - { property: 'photoFile', type: 'vich_image' }
